# Generated by Django 4.1.2 on 2022-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busStopInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('busStopNo', models.IntegerField(default=0)),
                ('busStopId', models.IntegerField(default=0)),
                ('busStopName', models.CharField(max_length=20)),
                ('gpsX', models.FloatField(default=0)),
                ('gpsY', models.FloatField(default=0)),
                ('busStopType', models.CharField(max_length=10)),
            ],
        ),
    ]
