# Generated by Django 4.1.2 on 2022-10-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunguard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstopinfo',
            name='busStopNo',
            field=models.IntegerField(default=0),
        ),
    ]
