# Generated by Django 4.1.2 on 2022-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunguard', '0002_busstopinfo_busstopno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstopinfo',
            name='gpsY',
        ),
        migrations.AlterField(
            model_name='busstopinfo',
            name='gpsX',
            field=models.FloatField(),
        ),
    ]
